project: "ncau-data-newsquery-prd"
project_nq: "ncau-data-newsquery-prd"
dataset: "sdm_optima_dgw"
dataset_nq: "sdm_optima"
startdate: "2026-02-16"
enddate: "2026-02-16"
startdate_nq: "2026-02-16"
enddate_nq: "2026-02-16"
output_csv: "output/"
skip_tables:
  - cart
  - order
deltaload_tables:
  - customer
  - customer_address
  - customer_address_ext
  - customer_ext
  - demographic
  - news_customer_contract
  - news_demographic_ex
  - news_ext_customer_redemption
  - news_financial_transaction
  - news_interactions
  - news_payment_account_ext
  - order_item
  - order_item_ext
  - order_item_note
  - paybreak
  - payment
  - payment_account
  - payment_reversed_payment
  - service
  - service_ext
# GBABA
  - gbaba_act_xref
# OPTIMA
  - audit_extract
  - pagination_extract
# RCTI
  - payonscan_bluebook_ext
  - rcti_7eleven_bluebook_ext
  - rcti_caltex_bluebook_ext
  - rcti_coles_bluebook_ext
  - rcti_coles_sm_bluebook_ext
  - rcti_woolies_bluebook_exts
# Adpoint
  - ad_custom_fields_export
  - customers_export
  - display_ads_export
  - insert_ads_export
  - online_ad_export2
  - order_custom_fields_export
  - order_export2
  - order_item_audience_segment
  - order_item_metadata
  - order_item_price_item
  - order_items
